modLoader="javafml"
loaderVersion="[46,)"

license="MIT"
issueTrackerURL="https://github.com/ZoeTheDaw/HalcyonHorizons/issues"
showAsResourcePack=false

[[mods]]
  modId="halcyonhorizons"
  version="1.0.0.0"
  displayName="Halcyon Horizons"
  updateJSONURL="https://files.minecraftforge.net/net/minecraftforge/forge/promotions_slim.json"
  displayURL=""
  logoFile="horizons_logo.png"
  credits="tissuebounce"
  authors="ZoeTheDaw, Trafficone"
  description='''
  Look up and explore the mysteries of the skies above.
  '''
  displayTest="MATCH_VERSION"

[[dependencies.alexscaves]] #optional
# the modid of the dependency
modId="citadel" #mandatory
# Does this dependency have to exist - if not, ordering below must be specified
mandatory=true #mandatory
# The version range of the dependency
versionRange="[2.6.0,)" #mandatory
# An ordering relationship for the dependency - BEFORE or AFTER required if the relationship is not mandatory
ordering="AFTER"
# Side this dependency is applied on - BOTH, CLIENT or SERVER
side="BOTH"

[[dependencies.alexscaves]]
modId="forge"
mandatory=true
versionRange="[47.1.3,)"
ordering="NONE"
side="BOTH"